/**
 * js/state.js
 * * يحتوي هذا الملف على حالة التطبيق الرئيسية (state)
 * وكائن الترجمة (translations) لسهولة الوصول إليهما من أي مكان.
 */

// كائن الحالة الرئيسي للتطبيق
export let state = {
    currentPage: 'home-page',
    products: [],
    receipts: [],
    bookings: [],
    salaries: {},
    salariesPaidStatus: {},
    expenses: {
        rent: { amount: 0, paidStatus: {} },
        // [--- إضافة ---] مصفوفة لتخزين المصاريف اليومية
        daily: [],
    },
    // [--- إضافة ---] مصفوفة لتخزين اليوميات المنتهية
    shifts: [],
    shiftDateFilter: '', // [--- إضافة ---]
    editingExpenseId: null, // [--- إضافة ---]
    bookingSearchTerm: '',
    salariesSearchTerm: '',
    selectedSalariesMonth: '',
    activeBookingId: null,
    activeReceiptId: null,
    editingBookingId: null,
    editingCustomerId: null,
    editingEmployeeUsername: null,
    editingSaleId: null,
    editingCartItem: null,
    sales: [],
    users: [],
    customers: [],
    lang: 'en', // Set default language to English
    editingProductId: null,
    returningSaleId: null,
    selectedSales: new Set(),
    currentUser: null,
    isAdminMode: false,
    categories: ['All'],
    activeCategory: 'All',
    itemToAdd: null,
    lastShiftReportTime: null,
    defects: [],
    stockAdjustmentData: null,
    // Supplier state
    suppliers: [],
    shipments: [],
    activeSupplierId: null,
    editingSupplierId: null,
    editingShipmentDate: null,
    editingPaymentId: null,
    editingShipmentInfo: null,
    supplierTimeFilter: 'all',
    supplierMonthFilter: '',
    supplierDayFilter: '',
    newInvoiceBuilder: {
        isOpen: false,
        supplierId: null,
        date: '',
        shippingCost: 0,
        items: [],
        editingItemIndex: null,
    },
    productModalSource: 'inventory', // لتتبع مصدر فتح نافذة المنتج
    lowStockThreshold: 5,
    returnActionData: null,
    newProductFormData: null,
};

// [جديد] دالة لتحديث الحالة بأكملها عند التحميل الأولي
export function setState(newState) {
    // دمج البيانات الجديدة مع الحفاظ على بعض الحالات المحلية
    const preservedState = {
        currentPage: state.currentPage,
        activeReceiptId: state.activeReceiptId,
        lang: state.lang,
        // أضف أي متغيرات أخرى تريد الحفاظ عليها هنا
    };
    state = { ...state, ...newState, ...preservedState };
}


// كائن الترجمة لجميع النصوص في التطبيق
export const translations = {
    en: {
        // [--- إضافة ---] نصوص جديدة لصفحة الإعدادات والنسخ الاحتياطي
        navSettings: 'Settings',
        settingsTitle: 'Application Settings',
        backupAndRestore: 'Backup & Restore',
        backupBtn: 'Backup Database',
        restoreBtn: 'Restore Database',
        backupSuccess: 'Backup created successfully at:',
        backupError: 'Backup failed:',
        restoreSuccess: 'Database restored successfully. The application will now restart.',
        restoreError: 'Restore failed:',
        // [--- إضافة ---] نصوص جديدة لليوميات
        navShifts: 'Shifts',
        addDailyExpense: 'Add Daily Expense',
        calculateCurrentShift: 'Calculate Current Shift',
        shiftHistory: 'Shift History',
        expenseAmount: 'Expense Amount',
        expenseNotes: 'Notes',
        saveExpense: 'Save Expense',
        currentShiftDetails: 'Current Shift Details',
        endAndReconcile: 'End & Reconcile Shift',
        shiftStart: 'Shift Start',
        totalSales: 'Total Sales',
        totalReturns: 'Total Returns',
        dailyExpenses: 'Daily Expenses',
        expectedCash: 'Expected in Drawer',
        cashReconciliation: 'Cash Reconciliation',
        actualCash: 'Actual Amount in Drawer',
        difference: 'Difference',
        deficit: 'Deficit',
        surplus: 'Surplus',
        confirmEndShift: 'Confirm & End Shift',
        shiftEndedSuccess: 'Shift ended successfully. Report saved.',
        shiftReport: 'Shift Report',
        shiftNumber: 'Shift #',
        endedBy: 'Ended By',
        reopenShift: 'Re-open Shift',
        confirmReopenShift: 'Are you sure you want to re-open this shift? The current open shift will be discarded.',
        // --- النصوص الحالية ---
        navHome: 'Home', navInventory: 'Inventory', navSelling: 'Selling', navBooking: 'Booking', navHistory: 'History', navCustomers: 'Customers', navSalaries: 'Salaries', navAbout: 'About', btnLogout: 'Logout', navBestSellers: 'Best Sellers', navDefects: 'Defects', navSuppliers: 'Suppliers',
        searchPlaceholder: 'Search by name, code, or barcode...',
        inventorySearchPlaceholder: 'Search inventory...',
        addNewProduct: 'Add New Product',
        colProductName: 'Name', colProductCode: 'Code', colCategory: 'Category', colImage: 'Image', colQuantity: 'Quantity', colPurchasePrice: 'Purchase Price', colSellingPrice: 'Selling Price', colColors: 'Colors', colActions: 'Actions',
        modalAddTitle: 'Add New Product', modalEditTitle: 'Edit Product',
        labelProductName: 'Product Name', labelCategory: 'Category', labelProductCode: 'Product Code (SKU)', labelBarcode: 'Main Barcode', labelProductImages: 'Product Images',
        labelColors: 'Colors & Stock', btnAddColor: '+ Add Color', labelColorName: 'Color',
        labelSizesForColor: 'Sizes for', labelSize: 'Size', labelQuantity: 'Quantity', btnAddSize: '+ Add Size',
        btnSave: 'Save', btnCancel: 'Cancel', btnOK: 'OK', btnEdit: 'Edit', btnDelete: 'Delete', btnYes: 'Yes', btnNo: 'No',
        addToCartTitle: 'Add Products to Cart', selectProduct: 'Select a product', color: 'Color', size: 'Size', sellingPrice: 'Selling Price (EGP)', addToCart: 'Add to Cart',
        addedToCart: 'Added!',
        barcodeScanner: 'Scan Barcode', barcodePlaceholder: 'Scan or type and press Enter...',
        cart: 'Cart',
        customerPhone: 'Customer Phone', customerName: 'Customer Name', customerAddress: 'Customer Address', colCustomerCity: 'City',
        subtotal: 'Subtotal:', discountPercent: 'Discount (%):', discountAmount: 'Discount (EGP):', total: 'Total:', paidAmount: 'Paid Amount (EGP)', paidAmountPlaceholder: 'Enter amount paid', completeSale: 'Complete Sale',
        paymentMethod: 'Payment Method', cash: 'Cash', instaPay: 'InstaPay', vCash: 'VCash',
        freeDelivery: 'Free Delivery', deliveryFee: 'Delivery Fee',
        deposit: 'Deposit (EGP)', saveBooking: 'Save as Booking', openBookings: 'Open Bookings', loadBooking: 'Load Booking', bookingSaved: 'Booking saved!',
        reports: 'Reports', timeFilter: 'Time Filter', allTime: 'All Time', byMonth: 'By Month', byDay: 'By Day', selectMonth: 'Select Month', selectDay: 'Select Day', cashier: 'Cashier', allUsers: 'All Users', exportPdf: 'Export Sales to PDF',
        totalRevenue: 'Total Revenue', totalProfit: 'Total Profit', totalItemsSold: 'Items Sold', totalReturnsValue: 'Returns Value',
        totalCashSales: 'Cash Sales',
        salesHistory: 'Sales History', searchReceiptsPlaceholder: 'Search by Receipt ID, Customer, or Cashier...',
        selectAll: 'Select All', deleteSelected: 'Delete Selected',
        userManagement: 'User Management', openUserManagement: 'Open User Management',
        btnReturn: 'Return', btnReturned: 'Returned', btnPrint: 'Print', btnBarcode: 'Barcodes',
        outOfStock: 'Out of Stock',
        manageCategories: 'Manage Categories', manageCategoriesTitle: 'Manage Categories',
        newCategoryName: 'New Category Name', addCategoryBtn: 'Add',
        existingCategories: 'Existing Categories', doneBtn: 'Done',
        categoryDeleteConfirm: 'Are you sure you want to delete this category? All products in this category will become uncategorized.',
        customersTitle: 'Customers',
        colCustomerName: 'Name', colCustomerPhone: 'Phone', colCustomerAddress: 'Address', colTotalItems: 'Total Items Bought', colLastPurchase: 'Last Purchase',
        filterByMonth: 'Filter by Month:', exportExcel: 'Export to Excel',
        sellerSummaryTitle: 'Seller Summary',
        processing: 'Processing...',
        exportInventory: 'Export Inventory Report',
        inventoryReportTitle: 'Inventory Report',
        colSoldThisMonth: 'Sold (Month)',
        colTotalSalesMonth: 'Total Sales (Month)',
        navAdminMode: 'Admin',
        calculateShift: 'Calculate Shift',
        shiftReportTitle: 'Shift Report',
        saveAsBooking: 'Save as Booking',
        confirmBookingTitle: 'Confirm Booking',
        confirmBookingMsg: 'Please enter the deposit amount to save this cart as a booking.',
        amountDue: 'Amount Due:',
        bookingDetails: 'Booking Details',
        printBooking: 'Print Booking',
        bookingInvoice: 'Booking Invoice',
        bookingSearchPlaceholder: 'Search by ID, name, or phone...',
        colUserName: 'User Name', colFixedSalary: 'Fixed Salary', colCommissionPerPiece: 'Commission / Piece', colPiecesSold: 'Pieces Sold', colTotalCommission: 'Total Commission', colTotalSalary: 'Total Salary',
        editBooking: 'Edit Booking',
        depositPaid: 'Deposit Paid:',
        amountRemaining: 'Amount Remaining:',
        totalInstaPaySales: 'InstaPay Sales',
        totalVCashSales: 'VCash Sales',
        totalFreeDeliveries: 'Free Deliveries',
        colBonus: 'Bonus',
        depositPaymentMethod: 'Deposit Method:',
        exportReturns: 'Export Returns to PDF',
        returnDate: 'Return Date:',
        originalSaleTotal: 'Original Sale Total:',
        netSaleAfterReturn: 'Net Sale After Return:',
        addEmployee: 'Add Employee',
        editEmployee: 'Edit Employee',
        employeeId: 'Employee ID',
        employeeName: 'Employee Name',
        employeePhone: 'Phone Number',
        colEmployeeId: 'Employee ID',
        deleteEmployeeConfirm: 'Are you sure you want to delete this employee?',
        paid: 'Paid',
        unpaid: 'Unpaid',
        addCustomer: 'Add Customer',
        editCustomer: 'Edit Customer',
        deleteCustomerConfirm: 'Are you sure you want to delete this customer? This action cannot be undone.',
        editCashier: 'Edit Cashier',
        grossProfit: 'Gross Profit',
        supplierPayments: 'Supplier Payments',
        totalSalaries: 'Salaries Expense',
        netIncome: 'Net Income',
        netProfit: 'Net Profit',
        rent: 'Monthly Rent',
        shippingExpense: 'Shipping Expense',
        totalExpenses: 'Total Expenses',
        totalProfit: 'Total Profit',
        stockAdjustConfirmTitle: 'Confirm Stock Reduction',
        stockAdjustMessage: 'You are reducing the stock for this item. How should this be handled?',
        deductCostOption: 'Deduct Cost & Remove from Stock',
        markDefectiveOption: 'Mark as Defective (Cost is not deducted)',
        cancelOption: 'Cancel',
        oldStockWarningTitle: 'Warning: Deducting from Old Stock',
        oldStockWarningMsg: 'You are about to reduce the quantity by more than what was added in the last batch. This will deduct costs from older inventory records. Do you want to proceed?',
        markAsDefectiveTitle: 'Mark Item as Defective',
        defectiveItemInfo: 'Item:',
        colDefectDate: 'Defect Date',
        colDefectReason: 'Reason',
        colReturnedStatus: 'Returned',
        btnSaveDefect: 'Save as Defective',
        totalDefectsCost: 'Defects Cost',
        manageSuppliers: 'Manage Suppliers',
        addSupplier: 'Add Supplier',
        editSupplier: 'Edit Supplier',
        supplierName: 'Supplier Name',
        supplierPhone: 'Supplier Phone',
        lastShipment: 'Last Shipment:',
        totalDue: 'Total Due:',
        makePayment: 'Make Payment',
        paymentAmount: 'Payment Amount',
        confirmPayment: 'Confirm Payment',
        shipmentInvoice: 'Shipment Invoice',
        invoiceId: 'Invoice ID',
        totalItems: 'Total Items',
        totalCost: 'Total Cost',
        assignToSupplier: 'Assign to Supplier',
        selectSupplier: 'Select a supplier for this stock increase.',
        freeDeliveryIndicator: 'Free Delivery',
        totalSuppliersDue: 'Total Suppliers Due',
        totalPaidToSuppliers: 'Total Paid to Suppliers',
        totalSuppliersBalance: 'Total Suppliers Balance',
        shipmentsFor: 'Shipments for',
        editSupplierDetails: 'Edit Supplier',
        deleteSupplier: 'Delete Supplier',
        confirmDeleteShipment: 'Are you sure you want to delete this invoice? This will deduct the item quantities from your stock.',
        confirmDeletePayment: 'Are you sure you want to delete this payment record?',
        confirmDeleteSupplier: 'Are you sure you want to delete this supplier and all their associated invoices and payments? This action cannot be undone.',
        editInvoice: 'Edit Invoice',
        invoiceDate: 'Invoice Date',
        paymentDate: 'Payment Date',
        paymentsList: 'Payments List',
        noPaymentsFound: 'No payments found for this period.',
        editPayment: 'Edit Payment',
        colPaymentDate: 'Date',
        colPaymentAmount: 'Amount',
        btnUndoDefect: 'Undo',
        confirmUndoDefect: 'Are you sure you want to undo this defect entry? This will return the item to stock and adjust expenses.',
        stockOfSelected: 'Stock of Selected:',
        lowStockWarning: 'Low stock warning for',
        itemsLeft: 'items left',
        returnTypeTitle: 'Return Type',
        returnTypeMessage: 'How do you want to handle this return?',
        returnToStock: 'Normal Return (to Stock)',
        returnAsDefective: 'Mark as Defective',
        freeDeliveryCostPrompt: 'Please enter the shipping cost you are covering for this free delivery.',
        detailedStock: 'Detailed Stock',
        operatingExpenses: 'Operating Expenses',
        totalReturnsCount: 'Returns:',
        totalSalariesPaid: 'Total Salaries Paid',
        shippingCostForShipment: 'Shipping Cost',
        supplierDefects: 'Defective Items',
        totalDefectsValue: 'Total Defects Value',
        addDefective: 'Add Defective',
        manageReturns: 'Manage Returns',
        addDefectiveItemTitle: 'Add Defective Item for Supplier',
        returnDefectiveItemsTitle: 'Return Defective Items to Supplier',
        quantityToReturn: 'Qty to Return',
        returnSelected: 'Return Selected',
        noDefectsToReturn: 'No defective items to return for this supplier.',
        item: 'Item',
        unreturnedQty: 'Unreturned Qty',
        confirmReturnDefects: 'Are you sure you want to return the selected items? This will create a credit note for the supplier.',
        colSupplier: 'Supplier',
        labelShipmentDate: 'Invoice Date',
        noShipmentsForProduct: 'No invoices found for this product from this supplier.',
        colReturnStatusToSupplier: 'Return Status',
        statusFullyReturned: 'Fully Returned',
        statusPartiallyReturned: 'Partially Returned',
        statusNotReturned: 'Not Returned',
        btnSaveChanges: 'Save Changes',
        categoryNameExists: 'This category name already exists.',
        editShipmentItem: 'Edit Item',
        splitInvoice: 'Split Selected',
        newQuantity: 'New Quantity',
        moveToNewInvoice: 'Move to new invoice',
        confirmDeleteItem: 'Are you sure you want to delete this item from the invoice? Stock will be adjusted.',
        confirmSplitInvoice: 'Are you sure you want to move the selected items to a new invoice?',
        selectItemsToSplit: 'Select items to move.',
        mergeInvoices: 'Merge Selected',
        confirmMergeInvoices: 'Are you sure you want to merge the selected invoices for this day into one?',
        selectInvoicesToMerge: 'Please select at least two invoices to merge.',
        printDailyInvoice: 'Print Daily Invoice',
        btnClearFields: 'Clear Fields',
        paymentMethodLabel: 'Payment:',
        defectsIndicator: 'Defects:',
        addNewInvoice: 'Add New Invoice',
        invoiceBuilderTitle: 'New Supplier Invoice',
        addProductToInvoice: 'Add Product to Invoice',
        addExistingProduct: 'Add Existing Product',
        addNewProductToInvoice: 'Add New Product',
        invoiceItems: 'Invoice Items',
        saveInvoice: 'Save Invoice',
        selectProductToAdd: 'Select Product to Add',
        productQuantities: 'Product Quantities',
        totalInvoiceCost: 'Total Invoice Cost',
        addToInvoice: 'Add to Invoice',
    },
    ar: {
        // ... (Arabic translations)
        // [--- إضافة ---] نصوص جديدة لصفحة الإعدادات والنسخ الاحتياطي
        navSettings: 'الإعدادات',
        settingsTitle: 'إعدادات التطبيق',
        backupAndRestore: 'النسخ الاحتياطي والاستعادة',
        backupBtn: 'نسخ احتياطي للبيانات',
        restoreBtn: 'استعادة البيانات',
        backupSuccess: 'تم إنشاء نسخة احتياطية بنجاح في:',
        backupError: 'فشل النسخ الاحتياطي:',
        restoreSuccess: 'تم استعادة البيانات بنجاح. سيتم إعادة تشغيل التطبيق الآن.',
        restoreError: 'فشلت الاستعادة:',
        // [--- إضافة ---] نصوص جديدة لليوميات
        navShifts: 'اليوميات',
        addDailyExpense: 'إضافة مصروف يومي',
        calculateCurrentShift: 'حساب اليومية الحالية',
        shiftHistory: 'سجل اليوميات',
        expenseAmount: 'قيمة المصروف',
        expenseNotes: 'ملاحظات',
        saveExpense: 'حفظ المصروف',
        currentShiftDetails: 'تفاصيل اليومية الحالية',
        endAndReconcile: 'إنهاء ومطابقة اليومية',
        shiftStart: 'بداية اليومية',
        totalSales: 'إجمالي المبيعات',
        totalReturns: 'إجمالي المرتجعات',
        dailyExpenses: 'المصاريف اليومية',
        expectedCash: 'المتوقع بالدرج',
        cashReconciliation: 'مطابقة الدرج',
        actualCash: 'المبلغ الفعلي بالدرج',
        difference: 'الفرق',
        deficit: 'عجز',
        surplus: 'زيادة',
        confirmEndShift: 'تأكيد وإنهاء اليومية',
        shiftEndedSuccess: 'تم إنهاء اليومية بنجاح. تم حفظ التقرير.',
        shiftReport: 'تقرير اليومية',
        shiftNumber: 'يومية رقم',
        endedBy: 'بواسطة',
        reopenShift: 'إعادة فتح اليومية',
        confirmReopenShift: 'هل أنت متأكد من إعادة فتح هذه اليومية؟ سيتم تجاهل اليومية المفتوحة حالياً.',
        // --- النصوص الحالية ---
        navHome: 'الرئيسية', navInventory: 'المخزن', navSelling: 'البيع', navBooking: 'الحجز', navHistory: 'السجلات', navCustomers: 'العملاء', navSalaries: 'الرواتب', navAbout: 'حول', btnLogout: 'تسجيل الخروج', navBestSellers: 'الأكثر مبيعاً', navDefects: 'التوالف', navSuppliers: 'الموردين',
        searchPlaceholder: 'البحث بالاسم أو الكود أو الباركود...',
        inventorySearchPlaceholder: 'البحث في المخزن...',
        addNewProduct: 'إضافة منتج جديد',
        colProductName: 'الاسم', colProductCode: 'الكود', colCategory: 'الفئة', colImage: 'صورة', colQuantity: 'الكمية', colPurchasePrice: 'سعر الشراء', colSellingPrice: 'سعر البيع', colColors: 'الألوان', colActions: 'إجراءات',
        modalAddTitle: 'إضافة منتج جديد', modalEditTitle: 'تعديل المنتج',
        labelProductName: 'اسم المنتج', labelCategory: 'الفئة', labelProductCode: 'كود المنتج (SKU)', labelBarcode: 'الباركود الرئيسي', labelProductImages: 'صور المنتج',
        labelColors: 'الألوان والمخزون', btnAddColor: '+ إضافة لون', labelColorName: 'اللون',
        labelSizesForColor: 'مقاسات لون', labelSize: 'مقاس', labelQuantity: 'كمية', btnAddSize: '+ إضافة مقاس',
        btnSave: 'حفظ', btnCancel: 'إلغاء', btnOK: 'موافق', btnEdit: 'تعديل', btnDelete: 'حذف', btnYes: 'نعم', btnNo: 'لا',
        addToCartTitle: 'إضافة منتجات للسلة', selectProduct: 'اختر منتج', color: 'اللون', size: 'المقاس', sellingPrice: 'سعر البيع (جنيه)', addToCart: 'أضف إلى السلة',
        addedToCart: 'تمت الإضافة!',
        barcodeScanner: 'مسح الباركود', barcodePlaceholder: 'امسح أو اكتب واضغط Enter...',
        cart: 'السلة',
        customerPhone: 'هاتف العميل', customerName: 'اسم العميل', customerAddress: 'عنوان العميل', colCustomerCity: 'المدينة',
        subtotal: 'المجموع الفرعي:', discountPercent: 'خصم (٪):', discountAmount: 'خصم (جنيه):', total: 'الإجمالي:', paidAmount: 'المبلغ المدفوع (جنيه)', paidAmountPlaceholder: 'أدخل المبلغ المدفوع', completeSale: 'إتمام البيع',
        paymentMethod: 'طريقة الدفع', cash: 'كاش', instaPay: 'InstaPay', vCash: 'VCash',
        freeDelivery: 'توصيل مجاني', deliveryFee: 'رسوم التوصيل',
        deposit: 'عربون (جنيه)', saveBooking: 'حفظ الحجز', openBookings: 'الحجوزات المفتوحة', loadBooking: 'تحميل الحجز', bookingSaved: 'تم حفظ الحجز!',
        reports: 'التقارير', timeFilter: 'تصفية بالوقت', allTime: 'كل الأوقات', byMonth: 'بالشهر', byDay: 'باليوم', selectMonth: 'اختر الشهر', selectDay: 'اختر اليوم', cashier: 'الكاشير', allUsers: 'كل المستخدمين', exportPdf: 'تصدير المبيعات PDF',
        totalRevenue: 'إجمالي الإيرادات', totalProfit: 'إجمالي الأرباح', totalItemsSold: 'القطع المباعة', totalReturnsValue: 'قيمة المرتجعات',
        totalCashSales: 'مبيعات الكاش',
        totalInstaPaySales: 'مبيعات InstaPay',
        totalVCashSales: 'مبيعات VCash',
        salesHistory: 'سجل المبيعات', searchReceiptsPlaceholder: 'البحث برقم الإيصال، العميل، أو الكاشير...',
        selectAll: 'تحديد الكل', deleteSelected: 'حذف المحدد',
        userManagement: 'إدارة المستخدمين', openUserManagement: 'فتح إدارة المستخدمين',
        btnReturn: 'إرجاع', btnReturned: 'تم الإرجاع', btnPrint: 'طباعة', btnBarcode: 'الباركودات',
        outOfStock: 'نفذ المخزون',
        manageCategories: 'إدارة الفئات', manageCategoriesTitle: 'إدارة الفئات',
        newCategoryName: 'اسم الفئة الجديدة', addCategoryBtn: 'إضافة',
        existingCategories: 'الفئات الحالية', doneBtn: 'تم',
        categoryDeleteConfirm: 'هل أنت متأكد من حذف هذه الفئة؟ سيتم إلغاء تصنيف جميع المنتجات في هذه الفئة.',
        customersTitle: 'العملاء',
        colCustomerName: 'الاسم', colCustomerPhone: 'الهاتف', colCustomerAddress: 'العنوان', colTotalItems: 'إجمالي المشتريات', colLastPurchase: 'آخر شراء',
        filterByMonth: 'فلترة بالشهر:', exportExcel: 'تصدير لإكسل',
        sellerSummaryTitle: 'ملخص البائعين',
        processing: 'جاري المعالجة...',
        exportInventory: 'تصدير تقرير المخزون',
        inventoryReportTitle: 'تقرير المخزون',
        colSoldThisMonth: 'المباع (شهرياً)',
        colTotalSalesMonth: 'إجمالي المبيعات (شهرياً)',
        navAdminMode: 'المدير',
        calculateShift: 'حساب اليومية',
        shiftReportTitle: 'تقرير اليومية',
        saveAsBooking: 'حفظ كحجز',
        confirmBookingTitle: 'تأكيد الحجز',
        confirmBookingMsg: 'الرجاء إدخال قيمة العربون لحفظ هذه السلة كحجز.',
        amountDue: 'المبلغ المتبقي:',
        bookingDetails: 'تفاصيل الحجز',
        printBooking: 'طباعة الحجز',
        bookingInvoice: 'فاتورة حجز',
        bookingSearchPlaceholder: 'البحث بالرقم، الاسم، أو الهاتف...',
        colUserName: 'اسم المستخدم', colFixedSalary: 'الراتب الثابت', colCommissionPerPiece: 'العمولة للقطعة', colPiecesSold: 'القطع المباعة', colTotalCommission: 'إجمالي العمولة', colTotalSalary: 'الإجمالي المستحق',
        editBooking: 'تعديل الحجز',
        depositPaid: 'العربون المدفوع:',
        amountRemaining: 'المبلغ المتبقي:',
        totalFreeDeliveries: 'التوصيلات المجانية',
        colBonus: 'المكافأة',
        depositPaymentMethod: 'طريقة دفع العربون:',
        exportReturns: 'تصدير المرتجعات PDF',
        returnDate: 'تاريخ الإرجاع:',
        originalSaleTotal: 'إجمالي الطلب الأصلي:',
        netSaleAfterReturn: 'صافي البيع بعد الإرجاع:',
        addEmployee: 'إضافة موظف',
        editEmployee: 'تعديل موظف',
        employeeId: 'الرقم الوظيفي',
        employeeName: 'اسم الموظف',
        employeePhone: 'رقم الهاتف',
        colEmployeeId: 'الرقم الوظيفي',
        deleteEmployeeConfirm: 'هل أنت متأكد من حذف هذا الموظف؟',
        paid: 'مدفوع',
        unpaid: 'غير مدفوع',
        addCustomer: 'إضافة عميل',
        editCustomer: 'تعديل عميل',
        deleteCustomerConfirm: 'هل أنت متأكد من حذف هذا العميل؟ لا يمكن التراجع عن هذا الإجراء.',
        editCashier: 'تعديل الكاشير',
        grossProfit: 'إجمالي الربح',
        supplierPayments: 'مدفوعات الموردين',
        totalSalaries: 'مصروفات الرواتب',
        netIncome: 'صافي الدخل',
        netProfit: 'صافي الربح',
        rent: 'الإيجار الشهري',
        shippingExpense: 'مصروفات الشحن',
        totalExpenses: 'إجمالي المصروفات',
        totalProfit: 'إجمالي الأرباح',
        stockAdjustConfirmTitle: 'تأكيد تعديل المخزون',
        stockAdjustMessage: 'أنت تقوم بإنقاص كمية هذا المنتج. كيف تريد التعامل مع هذا الإجراء؟',
        deductCostOption: 'خصم التكلفة وإزالة من المخزون',
        markDefectiveOption: 'تسجيل كتالف (لا يتم خصم التكلفة)',
        cancelOption: 'إلغاء',
        oldStockWarningTitle: 'تحذير: خصم من مخزون قديم',
        oldStockWarningMsg: 'أنت على وشك إنقاص كمية أكبر من التي تم إضافتها في آخر دفعة. هذا سيؤدي إلى خصم التكلفة من سجلات المخزون الأقدم. هل تريد المتابعة؟',
        markAsDefectiveTitle: 'تسجيل قطعة تالفة',
        defectiveItemInfo: 'المنتج:',
        colDefectDate: 'تاريخ التلف',
        colDefectReason: 'السبب',
        colReturnedStatus: 'تم إرجاعها',
        btnSaveDefect: 'حفظ كتالف',
        totalDefectsCost: 'تكلفة التوالف',
        manageSuppliers: 'إدارة الموردين',
        addSupplier: 'إضافة مورد',
        editSupplier: 'تعديل مورد',
        supplierName: 'اسم المورد',
        supplierPhone: 'هاتف المورد',
        lastShipment: 'آخر شحنة:',
        totalDue: 'الإجمالي المستحق:',
        makePayment: 'تسجيل دفعة',
        paymentAmount: 'قيمة الدفعة',
        confirmPayment: 'تأكيد الدفع',
        shipmentInvoice: 'فاتورة شحن',
        invoiceId: 'رقم الفاتورة',
        totalItems: 'إجمالي القطع',
        totalCost: 'التكلفة الإجمالية',
        assignToSupplier: 'تخصيص لمورد',
        selectSupplier: 'اختر مورد لهذه الزيادة في المخزون.',
        freeDeliveryIndicator: 'شحن مجاني',
        totalSuppliersDue: 'إجمالي مستحقات الموردين',
        totalPaidToSuppliers: 'إجمالي المدفوع للموردين',
        totalSuppliersBalance: 'الرصيد المتبقي للموردين',
        shipmentsFor: 'شحنات يوم',
        editSupplierDetails: 'تعديل المورد',
        deleteSupplier: 'حذف المورد',
        confirmDeleteShipment: 'هل أنت متأكد من حذف هذه الفاتورة؟ سيتم خصم كميات الأصناف من مخزونك.',
        confirmDeletePayment: 'هل أنت متأكد من حذف سجل الدفعة هذا؟',
        confirmDeleteSupplier: 'هل أنت متأكد من حذف هذا المورد وجميع فواتيره ومدفوعاته المرتبطة به؟ لا يمكن التراجع عن هذا الإجراء.',
        editInvoice: 'تعديل الفاتورة',
        invoiceDate: 'تاريخ الفاتورة',
        paymentDate: 'تاريخ الدفعة',
        paymentsList: 'قائمة المدفوعات',
        noPaymentsFound: 'لا توجد دفعات مسجلة لهذه الفترة.',
        editPayment: 'تعديل الدفعة',
        colPaymentDate: 'التاريخ',
        colPaymentAmount: 'المبلغ',
        btnUndoDefect: 'تراجع',
        confirmUndoDefect: 'هل أنت متأكد من التراجع عن هذا التالف؟ سيتم إرجاع القطعة إلى المخزون وتعديل المصروفات.',
        stockOfSelected: 'مخزون المحدد:',
        lowStockWarning: 'تحذير انخفاض المخزون لـ',
        itemsLeft: 'قطع متبقية',
        returnTypeTitle: 'نوع المرتجع',
        returnTypeMessage: 'كيف تريد التعامل مع هذا المرتجع؟',
        returnToStock: 'مرتجع عادي (للمخزن)',
        returnAsDefective: 'تسجيل كتالف',
        freeDeliveryCostPrompt: 'الرجاء إدخال تكلفة الشحن التي ستتحملها لهذا التوصيل المجاني.',
        detailedStock: 'المخزون التفصيلي',
        operatingExpenses: 'المصروفات التشغيلية',
        totalReturnsCount: 'المرتجعات:',
        totalSalariesPaid: 'إجمالي الرواتب المدفوعة',
        shippingCostForShipment: 'تكلفة الشحن',
        supplierDefects: 'التوالف',
        totalDefectsValue: 'إجمالي قيمة التوالف',
        addDefective: 'إضافة تالف',
        manageReturns: 'إدارة المرتجعات',
        addDefectiveItemTitle: 'إضافة تالف للمورد',
        returnDefectiveItemsTitle: 'إرجاع توالف للمورد',
        quantityToReturn: 'كمية الإرجاع',
        returnSelected: 'إرجاع المحدد',
        noDefectsToReturn: 'لا توجد توالف لإرجاعها لهذا المورد.',
        item: 'الصنف',
        unreturnedQty: 'الكمية المتبقية',
        confirmReturnDefects: 'هل أنت متأكد من إرجاع الأصناف المحددة؟ سيتم إنشاء إشعار دائن للمورد.',
        colSupplier: 'المورد',
        labelShipmentDate: 'تاريخ الفاتورة',
        noShipmentsForProduct: 'لا توجد فواتير لهذا المنتج من هذا المورد.',
        colReturnStatusToSupplier: 'حالة الإرجاع للمورد',
        statusFullyReturned: 'تم إرجاعه بالكامل',
        statusPartiallyReturned: 'مرتجع جزئي',
        statusNotReturned: 'لم يتم إرجاعه',
        btnSaveChanges: 'حفظ التعديلات',
        categoryNameExists: 'اسم الفئة هذا موجود بالفعل.',
        editShipmentItem: 'تعديل الصنف',
        splitInvoice: 'فصل المحدد',
        newQuantity: 'الكمية الجديدة',
        moveToNewInvoice: 'نقل إلى فاتورة جديدة',
        confirmDeleteItem: 'هل أنت متأكد من حذف هذا الصنف من الفاتورة؟ سيتم تعديل المخزون.',
        confirmSplitInvoice: 'هل أنت متأكد من نقل الأصناف المحددة إلى فاتورة جديدة؟',
        selectItemsToSplit: 'اختر الأصناف لنقلها.',
        mergeInvoices: 'دمج المحدد',
        confirmMergeInvoices: 'هل أنت متأكد من دمج الفواتير المحددة لهذا اليوم في فاتورة واحدة؟',
        selectInvoicesToMerge: 'الرجاء تحديد فاتورتين على الأقل للدمج.',
        printDailyInvoice: 'طباعة فاتورة اليوم',
        btnClearFields: 'مسح الحقول',
        paymentMethodLabel: 'الدفع:',
        defectsIndicator: 'توالف:',
        addNewInvoice: 'إضافة فاتورة جديدة',
        invoiceBuilderTitle: 'فاتورة مورد جديدة',
        addProductToInvoice: 'إضافة منتج للفاتورة',
        addExistingProduct: 'إضافة منتج حالي',
        addNewProductToInvoice: 'إضافة منتج جديد',
        invoiceItems: 'أصناف الفاتورة',
        saveInvoice: 'حفظ الفاتورة',
        selectProductToAdd: 'اختر المنتج للإضافة',
        productQuantities: 'كميات المنتج',
        totalInvoiceCost: 'التكلفة الإجمالية للفاتورة',
        addToInvoice: 'إضافة للفاتورة',
    }
};
